import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import variables from "./variables.module.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body style={{ 
        padding: 0,
        margin: 0,
        boxSizing: "border-box",
        height: "100vh", 
        backgroundColor: "#232549",
        display: "flex",
        alignItems: "center",
        justifyContent: "center"
      }}>
        {children}
      </body>
    </html>
  );
}
